# All services required to test myelectricaldata
version: "3.9"
services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    privileged: true
    restart: unless-stopped
    environment:
      TZ: Europe/Paris
    volumes:
      - ./config:/config
      - /run/dbus:/run/dbus:ro
    ports:
      - 8123:8123
  mqtt:
    image: emqx/nanomq:latest
    ports:
      - 1893:1883
      - 8093:8083
      - 8893:8883
